/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonaRouteImport } from './routes/zona'
import { Route as ReportarRouteImport } from './routes/reportar'
import { Route as RecompensasRouteImport } from './routes/recompensas'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const ZonaRoute = ZonaRouteImport.update({
  id: '/zona',
  path: '/zona',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportarRoute = ReportarRouteImport.update({
  id: '/reportar',
  path: '/reportar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecompensasRoute = RecompensasRouteImport.update({
  id: '/recompensas',
  path: '/recompensas',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/faq': typeof FaqRoute
  '/mapa': typeof MapaRoute
  '/recompensas': typeof RecompensasRoute
  '/reportar': typeof ReportarRoute
  '/zona': typeof ZonaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/faq': typeof FaqRoute
  '/mapa': typeof MapaRoute
  '/recompensas': typeof RecompensasRoute
  '/reportar': typeof ReportarRoute
  '/zona': typeof ZonaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/faq': typeof FaqRoute
  '/mapa': typeof MapaRoute
  '/recompensas': typeof RecompensasRoute
  '/reportar': typeof ReportarRoute
  '/zona': typeof ZonaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/faq'
    | '/mapa'
    | '/recompensas'
    | '/reportar'
    | '/zona'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/faq'
    | '/mapa'
    | '/recompensas'
    | '/reportar'
    | '/zona'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/faq'
    | '/mapa'
    | '/recompensas'
    | '/reportar'
    | '/zona'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  FaqRoute: typeof FaqRoute
  MapaRoute: typeof MapaRoute
  RecompensasRoute: typeof RecompensasRoute
  ReportarRoute: typeof ReportarRoute
  ZonaRoute: typeof ZonaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zona': {
      id: '/zona'
      path: '/zona'
      fullPath: '/zona'
      preLoaderRoute: typeof ZonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportar': {
      id: '/reportar'
      path: '/reportar'
      fullPath: '/reportar'
      preLoaderRoute: typeof ReportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recompensas': {
      id: '/recompensas'
      path: '/recompensas'
      fullPath: '/recompensas'
      preLoaderRoute: typeof RecompensasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  FaqRoute: FaqRoute,
  MapaRoute: MapaRoute,
  RecompensasRoute: RecompensasRoute,
  ReportarRoute: ReportarRoute,
  ZonaRoute: ZonaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from '../start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
